# Generated by Django 5.0.3 on 2024-03-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Years_1', models.CharField(blank=True, max_length=100, null=True)),
                ('Headline1', models.CharField(blank=True, max_length=100, null=True)),
                ('about1', models.TextField(blank=True, null=True)),
                ('Years_2', models.CharField(blank=True, max_length=100, null=True)),
                ('Headline2', models.CharField(blank=True, max_length=100, null=True)),
                ('about2', models.TextField(blank=True, null=True)),
                ('Years_3', models.CharField(blank=True, max_length=100, null=True)),
                ('Headline3', models.CharField(blank=True, max_length=100, null=True)),
                ('about3', models.TextField(blank=True, null=True)),
                ('Years_4', models.CharField(blank=True, max_length=100, null=True)),
                ('Headline4', models.CharField(blank=True, max_length=100, null=True)),
                ('about4', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AmazingTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(blank=True, max_length=100, null=True)),
                ('role1', models.CharField(blank=True, max_length=100, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='Team/')),
                ('twitter1', models.URLField(blank=True, max_length=150, null=True)),
                ('facebook1', models.URLField(blank=True, max_length=150, null=True)),
                ('linkeldin', models.URLField(blank=True, max_length=150, null=True)),
                ('name2', models.CharField(blank=True, max_length=100, null=True)),
                ('role2', models.CharField(blank=True, max_length=100, null=True)),
                ('image2', models.ImageField(blank=True, null=True, upload_to='Team/')),
                ('twitter2', models.URLField(blank=True, max_length=150, null=True)),
                ('facebook2', models.URLField(blank=True, max_length=150, null=True)),
                ('linkeldin2', models.URLField(blank=True, max_length=150, null=True)),
                ('name3', models.CharField(blank=True, max_length=100, null=True)),
                ('role3', models.CharField(blank=True, max_length=100, null=True)),
                ('image3', models.ImageField(blank=True, null=True, upload_to='Team/')),
                ('twitter3', models.URLField(blank=True, max_length=150, null=True)),
                ('facebook3', models.URLField(blank=True, max_length=150, null=True)),
                ('linkeldin3', models.URLField(blank=True, max_length=150, null=True)),
                ('closingRemark', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Copyright',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForThoseWho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(blank=True, max_length=100, null=True)),
                ('description1', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='ForThose/')),
                ('title_2', models.CharField(blank=True, max_length=100, null=True)),
                ('description2', models.TextField(blank=True, null=True)),
                ('image2', models.ImageField(blank=True, null=True, upload_to='ForThose/')),
                ('title_3', models.CharField(blank=True, max_length=100, null=True)),
                ('description3', models.TextField(blank=True, null=True)),
                ('image3', models.ImageField(blank=True, null=True, upload_to='ForThose/')),
            ],
        ),
        migrations.CreateModel(
            name='OurSocials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, max_length=150, null=True)),
                ('twitter', models.URLField(blank=True, max_length=150, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_name1', models.CharField(blank=True, max_length=100, null=True)),
                ('description1', models.TextField(blank=True, null=True)),
                ('Service_name2', models.CharField(blank=True, max_length=100, null=True)),
                ('description2', models.TextField(blank=True, null=True)),
                ('Service_name3', models.CharField(blank=True, max_length=100, null=True)),
                ('description3', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_1', models.CharField(blank=True, max_length=100, null=True)),
                ('description1', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='Testimonial/')),
                ('name_2', models.CharField(blank=True, max_length=100, null=True)),
                ('description2', models.TextField(blank=True, null=True)),
                ('image2', models.ImageField(blank=True, null=True, upload_to='Testimonial/')),
                ('name_3', models.CharField(blank=True, max_length=100, null=True)),
                ('description3', models.TextField(blank=True, null=True)),
                ('image3', models.ImageField(blank=True, null=True, upload_to='Testimonial/')),
            ],
        ),
    ]
